### PR TITLE
format integer into string in GetString method

### PR DESCRIPTION
**Pull request by h3110w0r1d**

### CODE REVIEW

**Comment by tarsisazevedo** [comment]
Hi @h3110w0r1d, thanks for the PR. Can you fix broken test and add tests for this case?

**Comment by h3110w0r1d** [comment]
one question: can i set invalidValue.kind as string|int|int64

**Comment by tarsisazevedo** [comment]
Yes, I think you can @h3110w0r1d :)

**Comment by h3110w0r1d** [comment]
#8

**Pull request merged**
